### PR TITLE
fix rerun-if-env-changed

### PR DESCRIPTION
**Pull request by cssivision**
fix https://github.com/alexcrichton/libz-sys/issues/21

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! I think some `rerun-if-changed` should also be printed though, right? (for files depended on)

**Comment by cssivision** [comment]
from http://doc.crates.io/build-script.html, `rerun-if-changed=PATH` 
Normally build scripts are re-run if any file inside the crate root changes, but this can be used to scope changes to just a small set of files. 

if the build script itself (or one of its dependencies) changes, then it's rebuilt and rerun unconditionally, so cargo:rerun-if-changed=build.rs is almost always redundant (unless you want to ignore changes in all other files except for build.rs).

**Comment by alexcrichton** [comment]
Yeah but the default behavior is turned off if any other `rerun-if-*` keys are printed (such as this env var), so we'll have to recover the behavior by manually informing about input files. I think also that pkg-config now has an option to turn on the env vars by default?

**Comment by cssivision** [comment]
you mean env use `rerun-if-env-changed` will turn off behavior  behavior of env `rerun-if-changed`?

**Comment by alexcrichton** [comment]
Yeah unfortunately usage of either key turns of the default behavior :(

**Comment by cssivision** [comment]
ok, i will fix this.

**Comment by alexcrichton** [comment]
Ok! While this also depends on files in zlib itself I think printing out just the build script is fine for now.

**Pull request merged**
